### ISSUE TITLE
Check / Uncheck checkbox not working on edit mode

### ISSUE THREAD

**Issue by MsFoued** [Silvanite/novafieldcheckboxes#21]
As the title says, i'm not able to check OR uncheck checkboxes in edit form 

Laravel version : 5.8.18

Code source :

public function fields(Request $request)
{

$fields = [];

$categories = Category::with('subCategories.factSheets')->get();

foreach ($categories as $category) 
{

$subCategoriesHaventFactSheets = $category->subCategories()->pluck('title', 'id')->toArray();

$checkBoxes [] = Checkboxes::make($category->category_name, 'sub_categories[]')
                ->options($subCategoriesHaventFactSheets)
                ->withoutTypeCasting()->hideFromIndex(); 

$fields [] = new Panel($category->category_name, $checkBoxes);
}

return $fields;
}

![Sans titre](https://user-images.githubusercontent.com/15153313/58799251-1e21c980-8605-11e9-8a62-edc49feb1cb7.png)

**Comment by MsFoued** [comment]
My bad 🤦‍♂️

I was storing checked values in db like "[1, 2, 3]" instead of ["1", "2", "3"]

So by fixing that the problem is solved ✔

**Comment by emad-sure** [comment]
@MsFoued am storing data the right way like this  ["1", "2", "3"] 
but am still having an issue when updating 

![image](https://user-images.githubusercontent.com/53175321/71851052-4ebb6b80-30de-11ea-9841-e8f54d4966ad.png)
